### ISSUE TITLE
Safari & 5k  issues with Hydrogrid

### ISSUE THREAD

**Issue by iandstanley** [doggydips/doggydips.co.uk#107]
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/6939289/23097463/67f1b662-f62c-11e6-89f4-7396eceb44cc.png)

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/6939289/23097467/747d3320-f62c-11e6-8b33-a8c38d43119b.png)

.. Then it behaves in chrome - throughout the transition from 5K down to mobile:

![pastedgraphic-3](https://cloud.githubusercontent.com/assets/6939289/23097472/83e34d04-f62c-11e6-901a-54297c4360cd.png)

**Comment by iandstanley** [comment]
@adrianstanley Could you try this again 

I have pushed new code to the [staging server](https://doggydips-staging.firebaseapp.com/team/)

I have set the outer div to 960px using an outer-container and set the width of the flex-box which contains each record to 440px (just under half allowing for the gutter)

It ought to force the page to display a maximum of 2 wide.

**Comment by adrianstanley** [comment]
That’s totally FUBAR on 5K Safari (see attached), but Chrome looks really nice in the new format!

Adrian
