### ISSUE TITLE
Client Registration testing

### ISSUE THREAD

**Issue by adrianstanley** [doggydips/doggydips.co.uk#114]
I just tried to test the website after it has been pushed into production and managed to submit a request - so overall it works.....

The query that I do have is that I decided not to accept the terms and conditions... should we allow either of these tick boxes to not be ticked... i.e. can they submit a request if they are not the legal owners or they do not accept the terms and conditions.

If we allow this, then the girls will need to be aware to enforce them to accept the terms and conditions prior to taking them on or check that they have permission from the legal owner?!

**Comment by iandstanley** [comment]
Updated the Google Form to require the TWO questions to be checked.

Examined registrations so far and all of them have checked both (except yours)

Google Form now shows an error if you try to submit without checking both
