### ISSUE TITLE
Request for access ─ access issue

### ISSUE THREAD

**Issue by iandstanley** [doggydips/doggydips.co.uk#126]
FYI - suspect there is an error with sharing of this document!

Begin forwarded message:

From: "Daniel White (via Google Docs)" <dannywhite9712@gmail.com>
Subject: Doggy Day Care & Walking - Request for access
Date: 23 February 2017 at 00:48:55 GMT
To: adrian@doggydips.co.uk
Reply-To: Daniel White <dannywhite9712@gmail.com>

**Comment by iandstanley** [comment]
Yeah I mistakenly allowed it to be searchable ─ should be fixed now as I have set it to view only. 

![screenshot 2017-02-23 at 14 55 16](https://cloud.githubusercontent.com/assets/6939289/23264112/2f99e1ae-f9d8-11e6-8f1b-57b66a2e53a7.png)

**Comment by adrianstanley** [comment]
I set it to searchable.. was only people in the organisation before!

**Comment by iandstanley** [comment]
Oops.Sorry
