### ISSUE TITLE
iPhone 5SE view (very small mobile)

### ISSUE THREAD

**Issue by adrianstanley** [doggydips/doggydips.co.uk#24]
Looking on the 5SE, header banner is very small and whilst in landscape mode, the text looks OK, in portrait, I just get "Welcome to"... pictures also need some work in mobile view (hydrotherapy page - pair of paws or little bit of dogs head - appreciate these are the final pictures - just putting initial feedack on mobile device as this is all I have access to at the moment. Slide up above When would hydrotherapy be beneficial is a nice shot of the tarp... again, will probably look OK on desktop, but just need to ensure that final graphics come out centred nicely with final images on small mobile devices.

Never been a fan of "mobile phone browser experience"... will take a look on a desktop when I get access to it tonight. Appreciate your probably looking at big picture right now - just a reminder feedback to look again with mobile apple browser

**Comment by iandstanley** [comment]
Yeah haven't looked much at the responsiveness of the site yet. 

Most of the <div>s will respond ok but images and overlaid text may need a media query and changes to look right.

**Comment by iandstanley** [comment]
Probably mostly OK now with other fixes ... need to do a final check against all mobile screens

**Comment by iandstanley** [comment]
@adrianstanley probably fixed now .. just need to check

**Comment by iandstanley** [comment]
@adrianstanley I have checked the site for bugs and I believe that they have all been addressed and we are ready to go live.

[https://doggydips-staging.firebaseapp.com/](https://doggydips-staging.firebaseapp.com/)

There are a few issues and possible things to look at still left in the issues register (like adding dog walking photos for day care) 

But those could be added later if needed. 

Are you happy I push the site to live?
